# swagger.yaml
openapi: 3.0.0
info:
  title: Cheat Buster API
  version: 1.0.0
  description: |-
    API for checking if someone has a dating profile.
    ## Development
    - **Base URL**: `http://localhost:3000/api`
servers:
  - url: http://localhost:3000/api
    description: Development server
paths:
  /search:
    get:
      tags:
        - Search
      summary: Search for users
      description: Search by email or first name
      parameters:
        - $ref: '#/components/parameters/emailParam'
        - $ref: '#/components/parameters/nameParam'
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
components:
  parameters:
    emailParam:
      name: email
      in: query
      description: User's email address
      required: false
      schema:
        type: string
        format: email
    nameParam:
      name: name
      in: query
      description: User's first name
      required: false
      schema:
        type: string
        minLength: 2
  responses:
    BadRequest:
      description: Invalid input parameters
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Invalid email address
    NotFound:
      description: User not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Phew! No matching profiles found.
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: john@example.com
        age:
          type: integer
          example: 30
        city:
          type: string
          example: New York
        picture:
          type: string
          format: uri
          example: https://randomuser.me/api/portraits/men/1.jpg